INSERT INTO department (id, title)
VALUES (1, 'Front Desk')
       (2, 'Nursing Staff')
       (3, 'Laboratory')
       (4, 'Billing')
       (5, 'Physician Staff')
       (6, 'Office Management')

INSERT INTO roles (title, salary, department_id) 
VALUES ('Receptionist', 35000, 1)
       ('Nurse Practicioner', 150000, 2)
       ('Registered Nurse', 65000, 2)
       ('Medical Biller', 50000, 4)
       ('Physician', 250000, 5)
       ('Medical Assistant', 35000, 2)
       ('Medical Technologist', 55000, 3)
       ('Clinical Manager', 100000, 6)

INSERT INTO employee (first_name, last_name, role_id, department_id, manager_id) 
VALUES ('Denart', 'Ifurung', 5, null )
       ('Edwin', 'Pietrowski', 3, 2 )
       ('Charles', 'Beatty', 5, null )
       ('Darren', 'Ifurung', 6, 8 )
       ('Yonatan', 'Bermudez', 4, 8 )
       ('Maria', 'Cruz', 2, 8)
       ('Janet', 'Reno', 1, 8 )
       ('Rukia', 'Kuchiki', 7, 8 )
       ('Riza', 'Hawkeye', 8, null)
       

